# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version here
      - image: circleci/elixir:1.5

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install ClickHouse
          command: |
            sudo apt-get install software-properties-common
            sudo apt-add-repository "deb http://repo.yandex.ru/clickhouse/deb/stable/ main/"
            sudo apt-get update
            sudo apt-get install clickhouse-server-common clickhouse-client --force-yes
            sudo service clickhouse-server start
      - run:
          name: Install ODBC driver
          command:  |
            sudo curl https://s3.us-east-2.amazonaws.com/roman.chudov.test/clickhouse/libclickhouseodbc-release-2018-02-01.so > ~/libclickhouseodbc.so
            sudo mv ~/libclickhouseodbc.so /usr/local/lib/clickhouse-odbc.so
            export CLICKHOUSE_ODBC_DRIVER=/usr/local/lib/clickhouse-odbc.so


      # specify any bash command here prefixed with `run: `
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: MIX_ENV=test mix compile
      - run: mix test